version: "3.3"
# services:
#   app:
#     build: .
#     # context: C:/Users/a.bouhrira/OneDrive - NUMERYX/Bureau/microserviceProjet/feedback_module/
#     container_name: app-feedback-container
#     command: >
#       sh -c "python C:/Users/a.bouhrira/OneDrive - NUMERYX/Bureau/microserviceProjet/feedback_module/manage.py makemigrations &&
#              python C:/Users/a.bouhrira/OneDrive - NUMERYX/Bureau/microserviceProjet/feedback_module/manage.py migrate &&
#              python C:/Users/a.bouhrira/OneDrive - NUMERYX/Bureau/microserviceProjet/feedback_module/manage.py runserver 0.0.0.0:8000"
#     ports:
#       - "80:8000"
#     # volumes:
#     #   - .:/usr/src/app
#     depends_on:
#       - db
services:
  app:
    build: 
      context: .
      dockerfile: C:/Users/a.bouhrira/OneDrive - NUMERYX/Bureau/microserviceProjet/feedback_module/Dockerfile
    container_name: app-feedback-container
    command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: "postgres:latest"
    container_name: feedback-db-container
    environment:
      # POSTGRES_PASSWORD: mypassword
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'

    volumes:
      - pgdb:/var/lib/postgresql/data


   
volumes:
  pgdb: