version: "3.9"
services:
#keycloak-databases: (ibrahim)
  postgresql:
    container_name: postgres1
    image: postgres:14.4
    restart: always
    ports:
      - "5433:5432"   # External port access for the development profile
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: keycloak

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    volumes:
      - D:\esprit\2eme-annee\microservice\OurWork\realm-export.json:/tmp/realm-export.json
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8081:8081"
    command: [ "start-dev", "--http-port=8081" ]
    depends_on:
      - postgres1
  postgres:
    container_name: db
    image: "postgres:14.4"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      # change this to your local path
      - postgres_data:/d/esprit/2eme-annee/microservice/OurWork/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    networks:
      - local
    ports:
      - "5432:5432"

  # keycloak:
  #   container_name: keycloak
  #   build:
  #     context: .
  #     args:
  #       KEYCLOAK_VERSION: 22.0.0
  #   command: ['start', '--optimized', '--import-realm']
  #   depends_on:
  #     - "postgres"
  #   environment:
  #     JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
  #     KC_DB_PASSWORD: postgres
  #     KC_DB_URL: jdbc:postgresql://postgres/keycloak
  #     KC_DB_USERNAME: postgres
  #     KC_HEALTH_ENABLED: 'true'
  #     KC_HTTP_ENABLED: 'true'
  #     KC_METRICS_ENABLED: 'true'
  #     KC_HOSTNAME_URL: http://localhost:8180
  #     KC_PROXY: reencrypt
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: password
  #   ports:
  #     - "8180:8080"
  #     - "8787:8787" # debug port
  #   networks:
  #     - local
  #   volumes:
  #     - ./my-test-realm-realm.json:/opt/keycloak/data/import/my-test-realm-realm.json

#eureuka server (ibrahim)
  eurekaserver:
    build:
      context: D:\esprit\2eme-annee\microservice\EurekaSever
    ports:
      - "8888:8761"
    image: "eur"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/


#auth micro (ibrahim): 
  auth-micro:
    build:
      context: D:\esprit\2eme-annee\microservice\OurWork\spring-app
    ports:
      - "8088:8761"
    image: "auth"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
#gateway micro (ibrahim): 
  gateway-micro:
    build:
      context: D:\esprit\2eme-annee\microservice\OurWork\API_GATEWAY_SERVE
    ports:
      - "9999:8761"
    image: "auth"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/


#shop-module(amani nasri):
        shop-micro:
    build:
      context: D:\microservice Project\ourProject\micro-shop
    ports:
      - "8083:8761"
    image: "shop"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/

networks:
  local:
    name: local
    driver: bridge

volumes:
  postgres_data:
