version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8082:80"

    networks:
      - my_network

  db:
    image: mysql:latest
    ports:
      - "5432:5432"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: shopdb
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
