# Use the official Python base image
FROM python:3.10

# Set the working directory





# Copy the application code
COPY . .
RUN pip install --upgrade pip
RUN pwd > aa.txt && cat aa.txt
# RUN pip install -r ./requirements.txt
# Expose the port the app will run on
EXPOSE 8000